from __future__ import annotations

from pathlib import Path


def write_structural_report(path: Path, *, summary: dict, settings: dict) -> None:
    metrics = summary.get("metrics", {}) if isinstance(summary.get("metrics"), dict) else {}
    run_context = summary.get("run_context", {}) if isinstance(summary.get("run_context"), dict) else {}
    lines = [
        "# Structural Compounding Lab Report",
        "",
        "## Executive Summary",
        "",
        f"- Symbol: `{summary.get('symbol', 'BTCUSDT')}`",
        f"- Execution timeframe: `{summary.get('execution_timeframe', settings.get('execution_timeframe', '1h'))}`",
        f"- Current equity: `{summary.get('current_equity', 0.0):.2f}`",
        f"- Locked profit: `{summary.get('locked_profit', 0.0):.2f}`",
        f"- Active trading capital: `{summary.get('active_trading_capital', 0.0):.2f}`",
        f"- Trade count: `{metrics.get('trade_count', 0)}`",
        f"- Win rate: `{metrics.get('win_rate', 0.0):.2%}`",
        f"- Profit factor: `{metrics.get('profit_factor', 0.0):.2f}`",
        f"- Average R: `{metrics.get('avg_r', 0.0):.2f}`",
        f"- Max drawdown: `{metrics.get('max_drawdown_pct', 0.0):.2%}`",
        "",
        "## Run Window",
        "",
        f"- Config analysis start: `{run_context.get('analysis_start_date')}`",
        f"- Config analysis end: `{run_context.get('analysis_end_date')}`",
        f"- Loaded execution start: `{run_context.get('loaded_history_start')}`",
        f"- Loaded execution end: `{run_context.get('loaded_history_end')}`",
        f"- Source CSV: `{summary.get('source_csv') or 'resolved from local history store'}`",
        "",
        "## Strategy Logic",
        "",
        "- structural levels are derived from pivots, rolling range anchors, and prior-session references",
        "- liquidity context comes from equal levels, sweeps, failed breaks, and reclaim logic",
        "- setup acceptance requires economically viable risk/reward rather than pattern presence alone",
        "- convexity adjusts risk and add-on budget instead of blindly pyramiding every winner",
        "- danger-aware cooldown can clear early only for strong aligned setups",
        "",
        "## Model Windows",
        "",
        f"- Structure window: `{run_context.get('structure_window_bars')}` bars",
        f"- Liquidity window: `{run_context.get('liquidity_window_bars')}` bars",
        f"- Setup window: `{run_context.get('setup_window_bars')}` bars",
        f"- Recent liquidity horizon: `{run_context.get('recent_liquidity_bars')}` bars",
        "",
        "## Artifact Counts",
        "",
        f"- Setups logged: `{summary.get('setup_count', 0)}`",
        f"- Structural levels logged: `{summary.get('level_count', 0)}`",
        f"- Liquidity events logged: `{summary.get('liquidity_event_count', 0)}`",
        f"- Add-on events: `{summary.get('add_on_event_count', 0)}`",
        f"- Profit locks: `{summary.get('profit_lock_count', 0)}`",
        f"- Cooldown events: `{summary.get('cooldown_event_count', 0)}`",
        "",
        "## Settings Snapshot",
        "",
        f"- Confirmation timeframes: `{settings.get('confirmation_timeframes', [])}`",
        f"- Base capital: `{settings.get('base_capital', 20000)}`",
        f"- Risk per trade pct: `{settings.get('risk', {}).get('risk_per_trade_pct', 0.01)}`",
        f"- Minimum RR: `{settings.get('risk', {}).get('minimum_rr', 1.5)}`",
        f"- Convexity enabled: `{settings.get('convexity', {}).get('enabled', True)}`",
        f"- Profit vault enabled: `{settings.get('profit_vault', {}).get('enabled', True)}`",
        "",
        "## Research Layer",
        "",
        "- momentum personality is research-only and never a hard gate by default",
        "- intelligent pullback accumulation compares original entry geometry against refined pullback geometry",
        "- compounding readiness is diagnostic only and does not mutate pyramiding or exits",
        "- execution cost sensitivity remains research-only and does not alter live/paper behavior",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
